// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwujkefkweovhqxxvnoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3dWprZWZrd2VvdmhxeHh2bm9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYwMjQ5MjUsImV4cCI6MjA4MTYwMDkyNX0.B8QO8hPRElivQugemsy8N0X13VvFr9ZjlDsXqNbFIpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});